### PR TITLE
Add TypeScript type definitions

### PR DESCRIPTION
**Pull request by Glazy**
Hey 👋 

First of all, great project!

I would like to use this in one of my TypeScript projects to help with debugging but I have had to write my own TypeScript types.

I thought I may as well push them up for anyone else who wants to use this library with TS :rocket:

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for creating a TypeScript definition. 🙌 Can you follow [this styleguide](https://github.com/sindresorhus/typescript-definition-style-guide)?

**Comment by Glazy** [comment]
@sindresorhus 

I have updated the definitions to match the style guide now :+1:

**Comment by Glazy** [comment]
Any update on this @sindresorhus? :eyes:

**Comment by sindresorhus** [comment]
Hey, sorry for the slow reply. I just had way too many PRs to review. I'm getting it down to a more manageable number now. I've manually merged in your changes and released: https://github.com/sindresorhus/unstated-debug/releases/tag/v0.4.0

**Pull request closed without merging**
